name: Build Main
on:
  push:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Build Release
      run: cargo build --release --verbose
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: host_colo_rs
        path: target/release/host_colo_rs
