---
# Automation for release
name: Release Build
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Named step
      - run: echo "Placeholder for ${{ github.repository }} release build"
